import turtle as t
color=input("Enter color of the table : ")
length=int(input('Enter the length of table(150-200): '))
breadth=int(input('Enter the breadth of table(10-20): '))
size=int(input('Enter size of the cake(less than the length of table): '))

def cake():
    #This is for the table
    t.speed(0)
    t.bgcolor('light green')
    t.fillcolor(color)
    t.begin_fill()
    t.forward(length/2)
    t.left(90)
    t.forward(breadth)
    t.left(90)
    t.forward(length)
    t.left(90)
    t.forward(breadth)
    t.left(90)
    t.forward(length/2)
    t.end_fill()


    #This part is for the legs of the table
    t.penup()
    t.fillcolor(color)
    t.begin_fill()
    t.goto((length/2)-20,0)
    t.pendown()
    t.right(90)
    t.forward(150)
    t.right(90)
    t.forward(10)
    t.right(90)
    t.forward(150)
    t.end_fill() 

    t.penup()
    t.fillcolor(color)
    t.begin_fill()
    t.goto((length/2)-50,0)
    t.right(180)
    t.pendown()
    t.forward(100)
    t.right(90)
    t.forward(10)
    t.right(90)
    t.forward(100)
    t.end_fill()

    t.penup()
    t.fillcolor(color)
    t.begin_fill()
    t.goto(-(length/2)+50,0)
    t.right(180)
    t.pendown()
    t.forward(100)
    t.left(90)
    t.forward(10)
    t.left(90)
    t.forward(100)
    t.end_fill()

    t.penup()
    t.fillcolor(color)
    t.begin_fill()
    t.goto(-(length/2)+20,0)
    t.right(180)
    t.pendown()
    t.forward(150)
    t.left(90)
    t.forward(10)
    t.left(90)
    t.forward(150)
    t.end_fill()

    #This is for the cake 
    t.penup()
    t.goto(0,breadth)
    t.pendown()
    t.fillcolor('yellow')
    t.begin_fill()
    t.right(90)
    t.forward(size/2)
    t.left(90)
    t.forward(size)
    t.left(90)
    t.forward(size)
    t.left(90)
    t.forward(size)
    t.left(90)
    t.forward(size)
    t.left(90)
    t.end_fill()

    t.fillcolor('brown')
    t.begin_fill()
    t.forward(size-30)
    t.left(90)
    t.forward(size)
    t.left(90)
    t.forward(size-30)
    t.end_fill()

    t.fillcolor('black')
    t.begin_fill()
    t.left(90)
    t.forward(size)
    t.left(90)
    t.forward(size-50)
    t.left(90)
    t.forward(size)
    t.left(90)
    t.forward(size-50)
    t.end_fill()

    t.fillcolor('pink')
    t.begin_fill()
    t.left(90)
    t.forward(size)
    t.left(90)
    t.forward(size-60)
    t.left(90)
    t.forward(size)
    t.left(90)
    t.forward(size-60)
    t.end_fill()


    #Code for the cherry 
    t.penup()
    t.goto(0,size+breadth)
    t.pendown()
    t.fillcolor('red')
    t.begin_fill()
    t.circle(5)
    t.end_fill()


    #This part is for the candle on the cake
    t.penup()
    t.goto(-10,breadth+size)
    t.pendown()
    t.fillcolor('white')
    t.begin_fill()
    t.left(90)
    t.forward(5)
    t.left(90)
    t.forward(20)
    t.left(90)
    t.forward(5)
    t.left(90)
    t.forward(20)
    t.end_fill()

    #This part is for the flame
    t.penup()
    t.fillcolor('orange')
    t.begin_fill()
    t.goto(-17,breadth+size+23)
    t.pendown()
    t.circle(5)
    t.end_fill()
    t.penup()
    t.home()
    input('')

    
def main():
    cake()
main()